name: Estrai dati A2A con Puppeteer e carica via FTP

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installa dipendenze
        run: npm install

      - name: Esegui scraping
        run: node scrape.js

      - name: Carica via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: .
          server-dir: /public_html/wp-content/uploads/
